const defaultQuestions = [
  "图书馆怎么借书？",
  "宿舍报修去哪里提单？",
  "社团纳新一般在什么时候开始？",
  "食堂晚上几点还有饭？",
];

const seedCorpus = [
  {
    id: "official-library-borrow-guide",
    title: "图书馆借阅与续借办理说明",
    type: "official",
    sourceName: "天津商业大学图书馆",
    sourceDomain: "lib.tjcu.edu.cn",
    url: "https://lib.tjcu.edu.cn/gk/borrow-guide.html",
    canonicalUrl: "https://lib.tjcu.edu.cn/gk/borrow-guide.html",
    publishedAt: "2026-03-01T02:00:00.000Z",
    updatedAt: "2026-03-18T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "recent",
    trustScore: 0.95,
    dedupKey: "lib-borrow-guide",
    snippet:
      "在馆藏系统确认图书状态后，可凭校园卡或读者码办理借阅；到期前可在线续借，逾期会影响后续借阅权限。",
    fullSnippet:
      "图书馆借阅流程通常包括登录馆藏检索系统、确认在馆状态、凭校园卡或读者码办理借阅。热门教材和工具书按照馆内规则限制外借，到期前可以在线续借，逾期会影响后续借阅与预约。",
    answer:
      "图书馆借书先确认图书处于可借状态，再使用校园卡或读者码办理借阅；如果快到期，可以在线续借，逾期会影响后续借阅权限。",
    keywords: ["图书馆", "借书", "借阅", "续借", "校园卡", "读者码", "馆藏"],
    relatedQuestions: ["图书馆自习座位怎么预约？", "借阅到期后还能续借吗？"],
  },
  {
    id: "official-library-seat-booking",
    title: "图书馆自习座位预约说明",
    type: "official",
    sourceName: "天津商业大学图书馆",
    sourceDomain: "lib.tjcu.edu.cn",
    url: "https://lib.tjcu.edu.cn/gk/seat-booking.html",
    canonicalUrl: "https://lib.tjcu.edu.cn/gk/seat-booking.html",
    publishedAt: "2026-02-20T02:00:00.000Z",
    updatedAt: "2026-04-08T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "fresh",
    trustScore: 0.95,
    dedupKey: "lib-seat-booking",
    snippet:
      "考试周可通过图书馆预约系统提前锁定自习座位，入馆后需要在规定时间内签到，超时会自动释放席位。",
    fullSnippet:
      "图书馆自习座位需要通过预约系统提前申请，考试周通常启用分时预约。预约成功后需要在规定时间内完成入馆签到，未签到的席位会自动释放给其他同学使用。",
    answer:
      "图书馆自习座位一般通过预约系统提前申请，入馆后还要按时签到；如果超过预约签到时限，系统会自动释放席位。",
    keywords: ["图书馆", "自习", "座位", "预约", "签到", "考试周"],
    relatedQuestions: ["图书馆怎么借书？", "考试周座位预约规则会变吗？"],
  },
  {
    id: "official-dorm-repair-service",
    title: "学生公寓报修与后勤服务流程",
    type: "official",
    sourceName: "天津商业大学后勤处",
    sourceDomain: "hqglc.tjcu.edu.cn",
    url: "https://hqglc.tjcu.edu.cn/info/dorm-repair.html",
    canonicalUrl: "https://hqglc.tjcu.edu.cn/info/dorm-repair.html",
    publishedAt: "2026-02-26T02:00:00.000Z",
    updatedAt: "2026-04-12T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "fresh",
    trustScore: 0.94,
    dedupKey: "dorm-repair-service",
    snippet:
      "宿舍水电、门锁、照明等问题可通过后勤报修入口提交工单，填写楼号、房间号和故障描述后等待派单。",
    fullSnippet:
      "学生公寓的水电、门锁、照明和公共设施故障通常通过后勤报修入口处理。提交工单时需要填写楼号、房间号、联系方式和故障描述，紧急问题按值班电话或值班室流程升级处理。",
    answer:
      "宿舍报修通常先通过后勤报修入口提单，写清楼号、房间号和故障描述；如果是停水停电或门禁故障这类紧急问题，再按值班渠道升级处理。",
    keywords: ["宿舍", "公寓", "报修", "后勤", "维修", "工单", "门禁", "停电"],
    relatedQuestions: ["宿舍热水和洗衣房在哪里看通知？", "紧急报修能直接打电话吗？"],
  },
  {
    id: "official-student-leave-process",
    title: "学生请假与离校审批说明",
    type: "official",
    sourceName: "天津商业大学学工部 / 学生处",
    sourceDomain: "xgb.tjcu.edu.cn",
    url: "https://xgb.tjcu.edu.cn/info/leave-process.html",
    canonicalUrl: "https://xgb.tjcu.edu.cn/info/leave-process.html",
    publishedAt: "2026-03-05T02:00:00.000Z",
    updatedAt: "2026-04-02T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "recent",
    trustScore: 0.97,
    dedupKey: "student-leave-process",
    snippet:
      "短期请假通常在学生事务系统提交申请，并按照辅导员、学院审批链完成审核；离校类申请需要补充去向和返校时间。",
    fullSnippet:
      "学生请假通常需要在学生事务系统发起申请，填写请假类型、离校时间、返校时间和事由。短期请假由辅导员和学院审核，跨节假日或离津类申请一般需要补充去向、联系方式和家长知情信息。",
    answer:
      "请假一般先在学生事务系统提交申请，再按辅导员和学院的审批链完成审核；如果涉及离校或跨节假日，通常还要补充去向和返校时间。",
    keywords: ["请假", "离校", "审批", "学生事务", "辅导员", "返校", "请假流程"],
    relatedQuestions: ["离校申请需要填哪些材料？", "节假日返校时间怎么报备？"],
  },
  {
    id: "official-scholarship-aid-guide",
    title: "奖助学金申请与材料提交流程",
    type: "official",
    sourceName: "天津商业大学学工部 / 学生处",
    sourceDomain: "xgb.tjcu.edu.cn",
    url: "https://xgb.tjcu.edu.cn/info/scholarship-aid.html",
    canonicalUrl: "https://xgb.tjcu.edu.cn/info/scholarship-aid.html",
    publishedAt: "2026-03-10T02:00:00.000Z",
    updatedAt: "2026-03-28T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "recent",
    trustScore: 0.97,
    dedupKey: "scholarship-aid-guide",
    snippet:
      "奖助学金通常按学期集中申报，学生需在学院通知节点前提交申请表、成绩证明和家庭经济情况材料。",
    fullSnippet:
      "奖助学金申请一般由学院统一组织，学生需要在规定时间内提交申请表、成绩证明、综合测评结果和家庭经济情况材料。国家资助、校内奖学金和专项补助的评审节点与材料要求可能不同，应以当期通知为准。",
    answer:
      "奖助学金通常按学院通知集中申报，常见材料包括申请表、成绩证明和家庭经济情况说明；不同资助类型的时间和材料会有差异，需要以当期通知为准。",
    keywords: ["奖学金", "助学金", "资助", "申请", "成绩证明", "经济困难", "材料"],
    relatedQuestions: ["家庭经济困难认定一般什么时候开始？", "奖学金申请需要成绩排名吗？"],
  },
  {
    id: "official-club-recruitment-plan",
    title: "学生社团纳新与招新活动安排",
    type: "official",
    sourceName: "天津商业大学团委 / 社团管理部门",
    sourceDomain: "www.tjcu.edu.cn",
    url: "https://www.tjcu.edu.cn/info/club-recruitment.html",
    canonicalUrl: "https://www.tjcu.edu.cn/info/club-recruitment.html",
    publishedAt: "2026-03-12T02:00:00.000Z",
    updatedAt: "2026-04-01T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "recent",
    trustScore: 0.93,
    dedupKey: "club-recruitment-plan",
    snippet:
      "社团纳新一般集中在新学期开学初，线下招新展位和线上报名表会同步开放，热门社团可能安排面试或试训。",
    fullSnippet:
      "学生社团纳新通常安排在新学期开学初，校级招新活动会统一发布时间地点。社团报名方式一般包括线下展位登记和线上表单报名，文体类和技术类社团可能需要面试、试训或作品展示。",
    answer:
      "社团纳新一般集中在新学期开学初，学校会统一发布招新活动时间和地点；报名既可能在线下展位，也可能走线上表单，热门社团还会安排面试或试训。",
    keywords: ["社团", "纳新", "招新", "百团大战", "报名", "面试", "试训"],
    relatedQuestions: ["社团招新表在哪里填？", "热门社团通常会面试吗？"],
  },
  {
    id: "official-canteen-service-hours",
    title: "食堂营业时间与节假日供餐安排",
    type: "official",
    sourceName: "天津商业大学后勤处",
    sourceDomain: "hqglc.tjcu.edu.cn",
    url: "https://hqglc.tjcu.edu.cn/info/canteen-hours.html",
    canonicalUrl: "https://hqglc.tjcu.edu.cn/info/canteen-hours.html",
    publishedAt: "2026-02-18T02:00:00.000Z",
    updatedAt: "2026-04-14T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "fresh",
    trustScore: 0.94,
    dedupKey: "canteen-service-hours",
    snippet:
      "工作日食堂窗口通常覆盖早中晚三餐，节假日和寒暑假会缩减部分窗口，夜间供餐以值班窗口安排为准。",
    fullSnippet:
      "食堂营业时间通常根据教学周调整，工作日覆盖早中晚三餐，部分窗口会延长到晚间。节假日、寒暑假和考试周的窗口数量与供餐时段会动态调整，夜间供餐以值班窗口或临时公告为准。",
    answer:
      "食堂平时会覆盖早中晚三餐，晚上是否还有饭主要看值班窗口安排；到了节假日、寒暑假或考试周，窗口数量和营业时间通常会缩减。",
    keywords: ["食堂", "营业时间", "晚饭", "窗口", "供餐", "节假日", "夜宵"],
    relatedQuestions: ["食堂晚上几点还有饭？", "节假日哪些窗口还开？"],
  },
  {
    id: "official-course-selection-guide",
    title: "选课调整与补退选办理说明",
    type: "official",
    sourceName: "天津商业大学教务处",
    sourceDomain: "jwc.tjcu.edu.cn",
    url: "https://jwc.tjcu.edu.cn/info/course-selection.html",
    canonicalUrl: "https://jwc.tjcu.edu.cn/info/course-selection.html",
    publishedAt: "2026-02-24T02:00:00.000Z",
    updatedAt: "2026-04-10T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "fresh",
    trustScore: 0.97,
    dedupKey: "course-selection-guide",
    snippet:
      "补退选通常在开学初的固定时间窗口开放，系统关闭后需要按学院和教务处流程提交调整申请。",
    fullSnippet:
      "选课与补退选一般在开学初设置固定开放窗口，学生需要在教务系统内完成课程增删。系统关闭后，如因培养方案、课程冲突或重修需要调整，通常需提交书面或线上申请并经学院与教务处审核。",
    answer:
      "补退选通常只有开学初那一段固定时间能直接在教务系统操作；如果错过系统窗口，就要按学院和教务处的流程补交调整申请。",
    keywords: ["选课", "补退选", "教务", "课程调整", "重修", "教务系统"],
    relatedQuestions: ["错过补退选还能改课吗？", "重修课需要单独申请吗？"],
  },
  {
    id: "community-dorm-life-tips",
    title: "新生宿舍生活经验帖",
    type: "community",
    sourceName: "天津商业大学吧",
    sourceDomain: "tieba.baidu.com",
    url: "https://tieba.baidu.com/p/987654321",
    canonicalUrl: "https://tieba.baidu.com/p/987654321",
    publishedAt: "2026-03-25T02:00:00.000Z",
    updatedAt: "2026-03-25T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "recent",
    trustScore: 0.62,
    dedupKey: "community-dorm-life-tips",
    snippet:
      "公开经验帖里提到，宿舍日常报修最好先截图保留工单，遇到高峰期可以同时联系楼管确认进度。",
    fullSnippet:
      "公开经验帖主要分享宿舍生活经验，例如报修后保留工单截图、和舍友统一时间等维修、必要时联系楼管确认派单进度。这类内容适合作为流程补充，但不能替代正式通知和后勤公告。",
    answer:
      "社区经验里比较常见的建议是报修后保留工单截图，遇到高峰期再联系楼管确认进度；这类经验能补充细节，但正式流程还是以后勤通知为准。",
    keywords: ["宿舍", "经验", "楼管", "报修", "工单", "新生", "生活"],
    relatedQuestions: ["宿舍用品一般需要提前准备什么？", "楼管联系方式在哪里看？"],
  },
  {
    id: "community-canteen-recommendations",
    title: "食堂窗口与晚间供餐经验整理",
    type: "community",
    sourceName: "知乎天津商业大学检索入口",
    sourceDomain: "zhihu.com",
    url: "https://www.zhihu.com/question/123456789",
    canonicalUrl: "https://www.zhihu.com/question/123456789",
    publishedAt: "2026-03-30T02:00:00.000Z",
    updatedAt: "2026-03-30T02:00:00.000Z",
    fetchedAt: "2026-04-20T02:00:00.000Z",
    lastVerifiedAt: "2026-04-20T02:00:00.000Z",
    freshnessLabel: "recent",
    trustScore: 0.58,
    dedupKey: "community-canteen-recommendations",
    snippet:
      "公开讨论里提到，晚间供餐常集中在少数值班窗口，考试周和周末时段变化会比较大。",
    fullSnippet:
      "食堂公开讨论主要补充窗口体感、排队时段和晚间供餐经验，例如晚间供餐常集中在少数值班窗口、考试周和周末变化较大。这类信息适合作为生活经验补充，最终时间仍应以后勤公告为准。",
    answer:
      "社区讨论普遍提到晚上还开餐的通常是少数值班窗口，考试周和周末变化更明显；如果要确认当天有没有饭，最好还是看后勤公告。",
    keywords: ["食堂", "窗口", "经验", "排队", "晚间", "考试周", "周末"],
    relatedQuestions: ["晚间供餐一般在哪个食堂？", "考试周食堂会延长营业吗？"],
  },
];

module.exports = {
  defaultQuestions,
  seedCorpus,
};
